name: Build iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS Simulator
        run: flutter build ios --simulator --debug

      - name: Package app for Appetize
        run: |
          mkdir -p build/ios/simulator_zip
          cd build/ios/iphonesimulator
          zip -r ../simulator_zip/VISTA.zip Runner.app

      - name: Upload Simulator App
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: build/ios/simulator_zip/VISTA.zip
          retention-days: 7
